### ISSUE TITLE
Comment section allows posting empty comments

### ISSUE THREAD

**Issue by sahil-arsss** [Debatreya/Pen-nd-Pixel#86]
### Describe the bug
The comment section allows users to post empty comments. When a user submits a comment without any text, the system should prevent the comment from being posted and display an error message.

### To Reproduce
1. Navigate to the ['Blog Post' page.](https://pen-nd-pixel.onrender.com/blog/6663e86909fe18de0f6f89ea)
2. Click on the Publish comment with an empty box.
3. Observe that an empty comment is posted.   ----> like this -""

 ### Expected behavior
The system should not post any comment if the input field is empty.

### Screenshots
![image](https://github.com/Debatreya/Pen-nd-Pixel/assets/173594227/2aa14f6d-eebf-424e-ba70-316b3584bc34)

**Comment by Debatreya** [comment]
Actually. Comment section has no backend connection 😅. 

We will consider that while integrating the backend. ..

**Comment by Debatreya** [comment]
@sahil-arsss would you like to contribute?

**Comment by Debatreya** [comment]
> Of course! 

Cool :| 
1. So just fork this repo, 
2. Clone it locally 
3. Create a branch that suits the features you are working on: like `feat/comments`

These are the basic steps I recommend so as production is not disturbed. 

@Aryawart-kathpal will give you the knowledge of the Routes related to `/comments` and required `env`

So go on.✨👍

Create a PR as you are finished implementing.
